#ifndef __SAMPLES_H__
#define __SAMPLES_H__

#define SAMPLE_SMPBEATADDED 31
#define SAMPLE_OPTIONSHORTORGAN2 55
#define SAMPLE_OPTIONSHORTORGAN3 56
#define SAMPLE_ROOT 57
#define SAMPLE_HIHATREVERSED 58
#define SAMPLE_OUNG1 59
#define SAMPLE_OUNG2 60
#define SAMPLE_OUNG3 61
#define SAMPLE_OUNG4 62
#define SAMPLE_OUNG5 63
#define SAMPLE_OUNG6 64
#define SAMPLE_JAHACRASH 66
#define SAMPLE_FLUTE 95
#define SAMPLE_TRIANGLE 100
#define SAMPLE_LOWCLARINET 101
#define SAMPLE_SELLOENSEMBLE 103
#define SAMPLE_CLEARCYMBAL 104
#define SAMPLE_CUCKOO 105
#define SAMPLE_RINGWHISTLE 109
#define SAMPLE_CREAK 111
#define SAMPLE_SPLOSH 117
#define SAMPLE_SNORTT 125
#define SAMPLE_FINLAND 145

#endif
